name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 15 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Test
      run: bundle exec rake

  codegen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Generate code
      run: bundle exec rake codegen
    - name: Check diff
      run: |
        if ! git diff --quiet; then
          echo "ERROR: Generated code is outdated" >&2
          exit 1
        fi
