name: Test

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 15 * * 5'

env:
  OBSWS_VERSION: '5.0.0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Download obs-websocket
      run: |
        fname=obs-websocket-${OBSWS_VERSION}-Ubuntu64.zip
        curl -LOfsS "https://github.com/Palakis/obs-websocket/releases/download/${OBSWS_VERSION}/$fname"
        sha256sum -c <<<"2ed02f98639b1160cd6eded084fb82a98bd12593bf3367e6769e999af61eb344 *./$fname"
        unzip "$fname"
      working-directory: /tmp
    - name: Install packages
      run: |
        sudo add-apt-repository -y ppa:obsproject/obs-studio
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends /tmp/obs-websocket-*.deb xvfb netcat-openbsd psmisc
    - name: Start OBS
      run: |
        spec/run_obs 4455 very-secure-password &
        for i in $(seq 15); do
          nc -z -w 1 localhost 4455 && exit
          sleep 1
        done
        exit 1
    - name: Test
      run: bundle exec rake
    - name: Run examples
      working-directory: examples/websocket-driver
      run: |
        bundle install
        bundle exec ruby ./main.rb ws://localhost:4455 very-secure-password
    - name: Stop OBS
      if: always()
      run: |
        killall -v obs || :
        sleep 3
    - name: Upload OBS logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: obs-studio-logs
        path: tmp/config/obs-studio/logs

  codegen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Generate code
      run: bundle exec rake codegen
    - name: Check diff
      run: |
        if ! git diff --quiet; then
          echo "ERROR: Generated code is outdated" >&2
          exit 1
        fi
